export const SETTINGS_CATEGORY_ACTIONS = {
	REQUEST_SETTINGS_CATEGORY_FETCH_ALL: 'REQUEST_SETTINGS_CATEGORY_FETCH_ALL',
	REQUEST_SETTINGS_CATEGORY_FETCH_BY_ID:
		'REQUEST_SETTINGS_CATEGORY_FETCH_BY_ID',
	REQUEST_SETTINGS_CATEGORY_CREATE: 'REQUEST_SETTINGS_CATEGORY_CREATE',
	REQUEST_SETTINGS_CATEGORY_UPDATE: 'REQUEST_SETTINGS_CATEGORY_UPDATE',
	REQUEST_SETTINGS_CATEGORY_DELETE: 'REQUEST_SETTINGS_CATEGORY_DELETE',
	RECEIVE_SETTINGS_CATEGORY_FETCH_ALL: 'RECEIVE_SETTINGS_CATEGORY_FETCH_ALL',
	RECEIVE_SETTINGS_CATEGORY_FETCH_BY_ID:
		'RECEIVE_SETTINGS_CATEGORY_FETCH_BY_ID',
	RECEIVE_SETTINGS_CATEGORY_CREATE: 'RECEIVE_SETTINGS_CATEGORY_CREATE',
	RECEIVE_SETTINGS_CATEGORY_UPDATE: 'RECEIVE_SETTINGS_CATEGORY_UPDATE',
	RECEIVE_SETTINGS_CATEGORY_DELETE: '  RECEIVE_SETTINGS_CATEGORY_DELETE',
};

export const requestFetchAllCategories = () => ({
	type: SETTINGS_CATEGORY_ACTIONS.REQUEST_SETTINGS_CATEGORY_FETCH_ALL,
	data: null,
});
export const requestFetchCategoryById = id => ({
	type: SETTINGS_CATEGORY_ACTIONS.REQUEST_SETTINGS_CATEGORY_FETCH_BY_ID,
	data: id,
});
export const requestCreateCategory = data => ({
	type: SETTINGS_CATEGORY_ACTIONS.REQUEST_SETTINGS_CATEGORY_CREATE,
	data: data,
});
export const requestUpdateCategory = (id, data) => ({
	type: SETTINGS_CATEGORY_ACTIONS.REQUEST_SETTINGS_CATEGORY_UPDATE,
	data: { id: id, data: data },
});
export const requestDeleteCategory = id => ({
	type: SETTINGS_CATEGORY_ACTIONS.REQUEST_SETTINGS_CATEGORY_DELETE,
	data: id,
});

// RECEIVE DATA
export const receiveFetchAllCategories = data => ({
	type: SETTINGS_CATEGORY_ACTIONS.RECEIVE_SETTINGS_CATEGORY_FETCH_ALL,
	data: data,
});
export const receiveFetchCategoryById = data => ({
	type: SETTINGS_CATEGORY_ACTIONS.RECEIVE_SETTINGS_CATEGORY_FETCH_BY_ID,
	data: data,
});
export const receiveCreateCategory = data => ({
	type: SETTINGS_CATEGORY_ACTIONS.RECEIVE_SETTINGS_CATEGORY_CREATE,
	data: data,
});
export const receiveUpdateCategory = data => ({
	type: SETTINGS_CATEGORY_ACTIONS.RECEIVE_SETTINGS_CATEGORY_UPDATE,
	data: data,
});
export const receiveDeleteCategory = data => ({
	type: SETTINGS_CATEGORY_ACTIONS.RECEIVE_SETTINGS_CATEGORY_DELETE,
	data: data,
});
