export const SETTINGS_COUNTRY_ACTIONS = {
	REQUEST_SETTINGS_COUNTRY_FETCH_ALL: 'REQUEST_SETTINGS_COUNTRY_FETCH_ALL',
	REQUEST_SETTINGS_COUNTRY_FETCH_BY_ID: 'REQUEST_SETTINGS_COUNTRY_FETCH_BY_ID',
	REQUEST_SETTINGS_COUNTRY_CREATE: 'REQUEST_SETTINGS_COUNTRY_CREATE',
	REQUEST_SETTINGS_COUNTRY_UPDATE: 'REQUEST_SETTINGS_COUNTRY_UPDATE',
	REQUEST_SETTINGS_COUNTRY_DELETE: '  REQUEST_SETTINGS_COUNTRY_DELETE',
	RECEIVE_SETTINGS_COUNTRY_FETCH_ALL: 'RECEIVE_SETTINGS_COUNTRY_FETCH_ALL',
	RECEIVE_SETTINGS_COUNTRY_FETCH_BY_ID: 'RECEIVE_SETTINGS_COUNTRY_FETCH_BY_ID',
	RECEIVE_SETTINGS_COUNTRY_CREATE: 'RECEIVE_SETTINGS_COUNTRY_CREATE',
	RECEIVE_SETTINGS_COUNTRY_UPDATE: 'RECEIVE_SETTINGS_COUNTRY_UPDATE',
	RECEIVE_SETTINGS_COUNTRY_DELETE: '  RECEIVE_SETTINGS_COUNTRY_DELETE',
};

export const requestFetchAllCountries = () => ({
	type: SETTINGS_COUNTRY_ACTIONS.REQUEST_SETTINGS_COUNTRY_FETCH_ALL,
	data: null,
});
export const requestFetchCountryById = id => ({
	type: SETTINGS_COUNTRY_ACTIONS.REQUEST_SETTINGS_COUNTRY_FETCH_BY_ID,
	data: id,
});
export const requestCreateCountry = data => ({
	type: SETTINGS_COUNTRY_ACTIONS.REQUEST_SETTINGS_COUNTRY_CREATE,
	data: data,
});
export const requestUpdateCountry = (id, data) => ({
	type: SETTINGS_COUNTRY_ACTIONS.REQUEST_SETTINGS_COUNTRY_UPDATE,
	data: { id: id, data: data },
});
export const requestDeleteCountry = id => ({
	type: SETTINGS_COUNTRY_ACTIONS.REQUEST_SETTINGS_COUNTRY_DELETE,
	data: id,
});

// RECEIVE DATA
export const receiveFetchAllCountries = data => ({
	type: SETTINGS_COUNTRY_ACTIONS.RECEIVE_SETTINGS_COUNTRY_FETCH_ALL,
	data: data,
});
export const receiveFetchCountryById = data => ({
	type: SETTINGS_COUNTRY_ACTIONS.RECEIVE_SETTINGS_COUNTRY_FETCH_BY_ID,
	data: data,
});
export const receiveCreateCountry = data => ({
	type: SETTINGS_COUNTRY_ACTIONS.RECEIVE_SETTINGS_COUNTRY_CREATE,
	data: data,
});
export const receiveUpdateCountry = data => ({
	type: SETTINGS_COUNTRY_ACTIONS.RECEIVE_SETTINGS_COUNTRY_UPDATE,
	data: data,
});
export const receiveDeleteCountry = data => ({
	type: SETTINGS_COUNTRY_ACTIONS.RECEIVE_SETTINGS_COUNTRY_DELETE,
	data: data,
});
