export const SETTINGS_CRAWLSTEPTYPE_ACTIONS = {
	REQUEST_SETTINGS_CRAWLSTEPTYPE_FETCH_ALL:
		'REQUEST_SETTINGS_CRAWLSTEPTYPE_FETCH_ALL',
	REQUEST_SETTINGS_CRAWLSTEPTYPE_FETCH_BY_ID:
		'REQUEST_SETTINGS_CRAWLSTEPTYPE_FETCH_BY_ID',
	REQUEST_SETTINGS_CRAWLSTEPTYPE_CREATE:
		'REQUEST_SETTINGS_CRAWLSTEPTYPE_CREATE',
	REQUEST_SETTINGS_CRAWLSTEPTYPE_UPDATE:
		'REQUEST_SETTINGS_CRAWLSTEPTYPE_UPDATE',
	REQUEST_SETTINGS_CRAWLSTEPTYPE_DELETE:
		'REQUEST_SETTINGS_CRAWLSTEPTYPE_DELETE',
	RECEIVE_SETTINGS_CRAWLSTEPTYPE_FETCH_ALL:
		'RECEIVE_SETTINGS_CRAWLSTEPTYPE_FETCH_ALL',
	RECEIVE_SETTINGS_CRAWLSTEPTYPE_FETCH_BY_ID:
		'RECEIVE_SETTINGS_CRAWLSTEPTYPE_FETCH_BY_ID',
	RECEIVE_SETTINGS_CRAWLSTEPTYPE_CREATE:
		'RECEIVE_SETTINGS_CRAWLSTEPTYPE_CREATE',
	RECEIVE_SETTINGS_CRAWLSTEPTYPE_UPDATE:
		'RECEIVE_SETTINGS_CRAWLSTEPTYPE_UPDATE',
	RECEIVE_SETTINGS_CRAWLSTEPTYPE_DELETE:
		'  RECEIVE_SETTINGS_CRAWLSTEPTYPE_DELETE',
};

export const requestFetchAllCrawlStepTypes = () => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.REQUEST_SETTINGS_CRAWLSTEPTYPE_FETCH_ALL,
	data: null,
});
export const requestFetchCrawlStepTypeById = id => ({
	type:
		SETTINGS_CRAWLSTEPTYPE_ACTIONS.REQUEST_SETTINGS_CRAWLSTEPTYPE_FETCH_BY_ID,
	data: id,
});
export const requestCreateCrawlStepType = data => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.REQUEST_SETTINGS_CRAWLSTEPTYPE_CREATE,
	data: data,
});
export const requestUpdateCrawlStepType = (id, data) => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.REQUEST_SETTINGS_CRAWLSTEPTYPE_UPDATE,
	data: { id: id, data: data },
});
export const requestDeleteCrawlStepType = id => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.REQUEST_SETTINGS_CRAWLSTEPTYPE_DELETE,
	data: id,
});

// RECEIVE DATA
export const receiveFetchAllCrawlStepTypes = data => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.RECEIVE_SETTINGS_CRAWLSTEPTYPE_FETCH_ALL,
	data: data,
});
export const receiveFetchCrawlStepTypeById = data => ({
	type:
		SETTINGS_CRAWLSTEPTYPE_ACTIONS.RECEIVE_SETTINGS_CRAWLSTEPTYPE_FETCH_BY_ID,
	data: data,
});
export const receiveCreateCrawlStepType = data => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.RECEIVE_SETTINGS_CRAWLSTEPTYPE_CREATE,
	data: data,
});
export const receiveUpdateCrawlStepType = data => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.RECEIVE_SETTINGS_CRAWLSTEPTYPE_UPDATE,
	data: data,
});
export const receiveDeleteCrawlStepType = data => ({
	type: SETTINGS_CRAWLSTEPTYPE_ACTIONS.RECEIVE_SETTINGS_CRAWLSTEPTYPE_DELETE,
	data: data,
});
